name: asistencia_guard
description: Sistema de Control de Asistencias con Reconocimiento Facial
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.5
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # CSV Export
  csv: ^5.1.1
  path_provider: ^2.1.1
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
